import {
  LayoutDashboard,
  TrendingUp,
  Brain,
  Code2,
  Wrench,
  UtensilsCrossed,
  Bot,
  Archive,
  Heart,
  Clock,
  Settings,
  Search,
  Bitcoin,
  ScanLine,
  Calculator,
  MessageSquareMore,
  Sparkles,
  QrCode,
  Braces,
  Globe,
  BookOpen,
  ExternalLink,
  Star,
  Grid3X3,
  List,
  Sun,
  Moon,
  Menu,
  X,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ArrowLeft,
  ArrowRight,
  Github,
  FileText,
  Play,
  Layers,
  Tag,
  Hash,
  AlertCircle,
  CheckCircle2,
  Clock4,
  Construction,
  Loader2,
  Plus,
  Trash2,
  RefreshCw,
  PanelLeftClose,
  PanelLeftOpen,
  FolderOpen,
  Image,
  Lock,
  Palette,
  Calendar,
  Database,
  Shield,
} from 'lucide-react';

export const Icons = {
  dashboard: LayoutDashboard,
  trading: TrendingUp,
  ai: Brain,
  development: Code2,
  utilities: Wrench,
  restaurant: UtensilsCrossed,
  automations: Bot,
  archive: Archive,
  favorites: Heart,
  recent: Clock,
  settings: Settings,
  search: Search,
  bitcoin: Bitcoin,
  scan: ScanLine,
  calculator: Calculator,
  chat: MessageSquareMore,
  sparkles: Sparkles,
  qrcode: QrCode,
  braces: Braces,
  globe: Globe,
  book: BookOpen,
  external: ExternalLink,
  star: Star,
  grid: Grid3X3,
  list: List,
  sun: Sun,
  moon: Moon,
  menu: Menu,
  close: X,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronDown: ChevronDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  github: Github,
  fileText: FileText,
  play: Play,
  layers: Layers,
  tag: Tag,
  hash: Hash,
  alertCircle: AlertCircle,
  checkCircle: CheckCircle2,
  clock: Clock4,
  construction: Construction,
  loader: Loader2,
  plus: Plus,
  trash: Trash2,
  refresh: RefreshCw,
  panelClose: PanelLeftClose,
  panelOpen: PanelLeftOpen,
  folder: FolderOpen,
  image: Image,
  lock: Lock,
  palette: Palette,
  calendar: Calendar,
  database: Database,
  shield: Shield,
};

const iconMap = {
  Bitcoin: Bitcoin,
  ScanLine: ScanLine,
  Calculator: Calculator,
  MessageSquareMore: MessageSquareMore,
  Sparkles: Sparkles,
  QrCode: QrCode,
  Braces: Braces,
  Globe: Globe,
  Bot: Bot,
  TrendingUp: TrendingUp,
  Brain: Brain,
  Code2: Code2,
  Wrench: Wrench,
  UtensilsCrossed: UtensilsCrossed,
  Archive: Archive,
  Heart: Heart,
  Clock: Clock,
  Settings: Settings,
  LayoutDashboard: LayoutDashboard,
  Lock: Lock,
  Palette: Palette,
  Calendar: Calendar,
};

export function getIcon(name) {
  return iconMap[name] || Globe;
}
