import {
  TrendingUp,
  Brain,
  Code2,
  Wrench,
  UtensilsCrossed,
  Bot,
  Archive,
  Heart,
  Clock,
  Settings,
  Bitcoin,
  ScanLine,
  Calculator,
  MessageSquareMore,
  Sparkles,
  QrCode,
  Braces,
  Globe,
  LayoutDashboard,
  Lock,
  Palette,
  Calendar,
  Image,
  Mail,
  BookOpen,
  Leaf,
  GitBranch,
  Box,
  FileText,
  Zap,
  RefreshCw,
} from 'lucide-react';

const iconMap = {
  Bitcoin: Bitcoin,
  ScanLine: ScanLine,
  Calculator: Calculator,
  MessageSquareMore: MessageSquareMore,
  Sparkles: Sparkles,
  QrCode: QrCode,
  Braces: Braces,
  Globe: Globe,
  Bot: Bot,
  TrendingUp: TrendingUp,
  Brain: Brain,
  Code2: Code2,
  Wrench: Wrench,
  UtensilsCrossed: UtensilsCrossed,
  Archive: Archive,
  Heart: Heart,
  Clock: Clock,
  Settings: Settings,
  LayoutDashboard: LayoutDashboard,
  Lock: Lock,
  Palette: Palette,
  Calendar: Calendar,
  Image: Image,
  Mail: Mail,
  BookOpen: BookOpen,
  Leaf: Leaf,
  GitBranch: GitBranch,
  Box: Box,
  FileText: FileText,
  Zap: Zap,
  RefreshCw: RefreshCw,
};

export function getIcon(name) {
  return iconMap[name] || Globe;
}
